### PR TITLE
get message from view context

### PR DESCRIPTION
**Pull request by ferdy-lw**
Use message from view instead of controller

### CODE REVIEW

**Comment by dmathieu** [comment]
Are there many more of these ? It would be cool to have them all merged at once.
cc @jzajpt

**Comment by ferdy-lw** [comment]
There is a triple "{{{" in ModalPane body view template

**Comment by dmathieu** [comment]
Actually, that is intended. Triple { says the html is safe and shouldn't be escaped.
Without the triple {, we couldn't have html in the modal panes.

**Comment by ferdy-lw** [comment]
OK - I RTFM.  My commit needs to be changed as I removed the triple from the alert message and I think it should still be there in this case too.

Let me know if you want me to repush the change and readd the triple stash.

**Comment by dmathieu** [comment]
Damn, I didn't notice that.
Yes, it'd be cool to readd the triple. Don't worry, I'll do it right now form the inline github interface.
Thanks :sunflower:

**Pull request merged**
