### PR TITLE
Animation support for modal backdrop

### PR DESCRIPTION
**Pull request by flynfish**
Allows you to specify an animateBackdropIn and animateBackdropOut when displaying a modal.

### CODE REVIEW

**Comment by dmathieu** [comment]
Thank you! :yum:

Could you add tests checking that adding/removing the modal with those options still works?
Indeed you cannot test that the animation works. I just want to make sure removing the modal actually removes it.

**Comment by flynfish** [comment]
I tried running the tests, but when visiting `http://localhost:9292/tests/index.html?package=ember-bootstrap` I get:
 `Entity not found: /tests/index.html`

I don't see index.html in the code, is this the correct url? 

One other question, are you trying to keep the modal from using the bootstrap js files? I ask because it could support the default animations if instantiating the modal with the $('class').modal("show")

**Comment by dmathieu** [comment]
Sorry about the inadequate information in the README. Go to `http://localhost:9292`, that's the uri for the tests now.
I'll update it soon.

We want to avoid using bootstrap.js indeed. While for now, we don't care about backward compatibility, we will have to soon.
Therefore, caring about compatibility for one library (emberjs) is enough. I don't want to overcomplicate things with backward compatibility to bootstrap too.

**Comment by flynfish** [comment]
@dmathieu I think that test should do it, let me know what you think.

**Comment by dmathieu** [comment]
:+1: Thank you!

**Pull request merged**
