### PR TITLE
Be able to add classes to form elements: input, label ... etc.

### PR DESCRIPTION
**Pull request by ghost**
E.g. be able to achive http://goo.gl/uRb2L instead of http://goo.gl/e8UVa by ...

`{{view Bootstrap.Forms.TextField valueBinding="myObject.content" label="content" classNamesToAdd="span12"}}`.

### CODE REVIEW

**Comment by bradleypriest** [comment]
A couple of things, firstly we never merge new code without corresponding tests. But more importantly can we get a code example rather than screenshots.

**Comment by ghost** [comment]
@bradleypriest sorry about not testing this.

Did you mean a usage example or?, coz this (also above) looks enough to me:

`{{view Bootstrap.Forms.TextField valueBinding="myObject.content" label="content" classNamesToAdd="span12"}}`.

**Comment by bradleypriest** [comment]
I mean, what HTML are you trying to produce, I think you might be misusing the span12 class and would just be better off creating a CSS rule to achieve what you want. I'm just not sure this added complexity is worth putting into ember-bootstrap if it's an edge case.

``` css
.control-group label, .control-group input, .control-group textarea, .control-group select{
  width: 100%;
}
```

**Comment by ghost** [comment]
I tried :cry:  ... just that, I hate "messing" up the already provided grid system.

**Comment by bradleypriest** [comment]
That's why I was asking to see the HTML you wanted, if you're using a `span12` that is not directly a child of a `row-fluid`, you're not actually using the grid system. And if you are then maybe there is something to this request.

**Comment by dmathieu** [comment]
Also, you don't need to specify a span12 class directly to the input. You could use the class `input-block-level` on it, and then specify the span you want on the parent of the control-group.
So you get an HTML like this :

```
<div class="span12">
  <div class="control-group">
    <div class="controls"><input class="input-block-level" /></div> <!-- Here, the input has a width similar to the span12
  </div>
</div>
```

However, we actually can't add an input-block-level to the input. I believe this would be interesting, with an implementation similar to :

```
{{view Bootstrap.Forms.TextField valueBinding="content" label="content" inputClassNames="input-block-level"}}
```

**Comment by ghost** [comment]
Oh, sorry. Something like ...

```
<form class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="inputEmail" class="span12">Email</label>
    <div class="controls">
      <input type="text" id="inputEmail" placeholder="Email" class="span12">
    </div>
  </div>
</form>
```

etc.

I guess my goal is to be able to size controls as suggested http://goo.gl/SdFGO .

**Comment by dmathieu** [comment]
Well, my experience on bootstrap showed that adding spans directly to inputs poses problems as all elements aren't aligned properly.
[input-block-level](https://github.com/twitter/bootstrap/blob/master/less/mixins.less#L154) fixes this problem.

**Comment by ghost** [comment]
Will, try that out, and would prefer I pass it down as you suggested.

**Pull request closed without merging**
