### PR TITLE
Add PasswordField

### PR DESCRIPTION
**Pull request by schmidp**
I added support for <input type="password">.

### CODE REVIEW

**Comment by dmathieu** [comment]
Allowing different types of inputs is an awesome idea, thank you.
However, this implementation would mean we'd have to add email, numeric, ... all the html5 available types.
See http://www.w3.org/wiki/HTML5_form_additions

I believe it'd be better to allow the use of a diffent type for some fields :

```
{{view Bootstrap.Forms.TextField type="password" ...
```

It would allow all possible and imaginable types. And would make it possible to change the type at runtime.

**Comment by schmidp** [comment]
You are absolutely right. I'll see if I have time to implement this.

**Comment by dmathieu** [comment]
I'm closing this pull request then.
One more thing : if we add a dynamic type, TextField doesn't seem to be an appropriate name anymore.
I don't have a better name yet, but if you find one, it'd be cool.

**Comment by dmathieu** [comment]
FYI, I had forgotten about it, but it is already implemented.
https://github.com/emberjs-addons/ember-bootstrap/blob/master/packages/ember-bootstrap/tests/forms/controls/text_field_test.js#L45-54

**Pull request closed without merging**
