### PR TITLE
Updated bind code for Bootstrap.NavList

### PR DESCRIPTION
**Pull request by JamesWednesday**
### Notes

Added bindAttr for href & class to allow objects passed to be easily used instead of just text labels for the Navigation link.

I had to update view.title to view.content.title

Items passed into the NavList content array should be Objects, not just text.
### Bootstrap.NavList Example

``` html
<script type="text/x-handlebars">
  {{view Bootstrap.NavList
      contentBinding="SampleApp.navController.content"
      selectionBinding="SampleApp.navController.selection"}}
</script>
```

``` javascript

var siteNavigation = [
  {title: "Nav A", href: "#/RouteA"},
  {title: "Nav B", href: "#/RouteB"},
  {title: "Nav C", href: "#/RouteC",class:"last-child-hack-for-ie6"}
];

SampleApp.PrimaryNav = Bootstrap.NavList.create({
        elementId: ['primary-navigation'],
        content: siteNavigation,
        selectionBinding: "SampleApp.NavController.selection"
    });
```

Similar updates could be made to Pills, Tabs and other items with links.

### CODE REVIEW

**Comment by dmathieu** [comment]
What's the point of the comment ?

**Comment by JamesWednesday** [comment]
Its just to illustrate the update and what use it is.

**Comment by dmathieu** [comment]
I like the idea of this.
However, I'm wondering if it'd not be more readable and extendable to make the link an `Ember.View` object, instead of an handlebars compiled object.

**Comment by JamesWednesday** [comment]
The views are going to be fairly well defined by the way bootstrap mark's up its html. 
Moving the code to separate views would make it easier to track bootstrap versions as they progress.

I look forward to see if you take this route further.

**Comment by dmathieu** [comment]
Sorry for the delay, I just implemented this in 4858949529f5c472ed3a646b45385acbf0a4c92b

**Pull request closed without merging**
