### PR TITLE
Breadcrumb, Pager and Pagination

### PR DESCRIPTION
**Pull request by karlguillotte**
- Added tests for those new classes
- Create folder mixins, added mixins and refactor existing
  classes with mixins
- Modify README
- Modify sample (rake sample)

### CODE REVIEW

**Comment by dmathieu** [comment]
This is very interesting. I can't merge it though, there seems to be a conflict between master and your fork.

**Comment by karlguillotte** [comment]
I started from a complete new fork 10 days ago. Until yesterday this repo has not been updated since, so my fork and this repo was identical. Maybe it is due to files that I moved to the new mixins folder. Do you have more information about the conflicts?

**Comment by dmathieu** [comment]
No, I don't. It's just what the github interface says.
I believe it would be because of other commits which happened in the past 10 days.

**Comment by karlguillotte** [comment]
Hi,

With those new commits, is it possible to automatically merge? 

Thanks

**Comment by dmathieu** [comment]
Hey, did you run the specs before sending your pull request ? [they are failing with your commits](http://travis-ci.org/#!/jzajpt/ember-bootstrap/builds/1543750).
Could you fix the problem and submit an other pull request please ?

**Comment by karlguillotte** [comment]
Hi,

I always do. However, those last two commits are pull I received. I will get the latest tonight, fix the issue and pull again. Thanks for letting me know. 

Karl

**Pull request merged**
